project:
 type: website

website:
 title: "prattashaislam.github.io"
 navbar:
  left:
    - href: index.qmd
      text: Home
    - href: assignments.qmd
      text: Data Visualization Assignments and Project
    - href: Info Management_Proposal Presentation.pdf
      text: Info Management Proposal Presentation
    - href: Info Management_Final Presentation.pdf
      text: Info Management Final Presentation
    - href: Islam_Final_Paper_EPPS 6354.pdf
      text: Info Management Final Project Paper
    - text: Info Management Assignments
      menu:
        - href: EPPS 6354_Assignment 1_Prattasha.pptx
          text: Assignment 1
        - href: EPPS 6354_Assignment 2_Prattasha.pptx
          text: Assignment 2
        - href: EPPS 6354_Assignment 3_Prattasha.pptx
          text: Assignment 3
        - href: EPPS 6354_Assignment 4_Prattasha.pptx
          text: Assignment 4
        - href: EPPS 6354_Assignment 5_Prattasha.pptx
          text: Assignment 5

  

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

